# Starter pipeline
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'Viresh ASoC'
    applications: '94614bb6-7805-4655-8d29-7a72f95a144d'
    scanname: 'CA Demo DevSecOps Demo1'
    scantype: 'static'
    scanMethod: 'IRX'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'Viresh ASoC'
    applications: '94614bb6-7805-4655-8d29-7a72f95a144d'
    scanname: 'AzureDevOps Scan1'
    scantype: 'dynamic'
    dynamicType: 'DAST'
    scanURL: 'https://demo.testfire.net/'
    network: 'public'
    optimization: 'fastest'
    email: true